// The long tracts above C1, the cranial nerve nuclei and the named territories (P5). Data only.
// Steps run in the direction the signal travels: descending routes from the cortex down,
// ascending routes from the medulla up.
import type { Brain } from './types.ts';

const p = 'pending' as const;

export const BRAIN: Brain = {
  corticospinal: {
    meta: {
      id: 'brain.corticospinal',
      claim: 'The corticospinal tract runs from the motor cortex through the posterior limb of the internal capsule, the cerebral peduncle, the basis pontis and the pyramid, and crosses at the medullary–spinal junction, so a lesion above serves the other side of the body.',
      sources: ['S54', 'S48'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'cortex', compartment: 'motor_cortex' }, { level: 'capsule', compartment: 'capsule_posterior_motor' }, { level: 'midbrain', compartment: 'peduncle' }, { level: 'pons', compartment: 'basis' }, { level: 'medulla', compartment: 'pyramid' }],
    serves: 'contralateral',
  },
  lemniscal: {
    meta: {
      id: 'brain.lemniscal',
      claim: 'After crossing in the caudal medulla the medial lemniscus ascends contralaterally to VPL, which projects through the posterior limb to the somatosensory cortex.',
      sources: ['S57', 'S56'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [
      { level: 'medulla', compartment: 'medial_lemniscus' },
      { level: 'pons', compartment: 'medial_lemniscus' },
      { level: 'midbrain', compartment: 'medial_lemniscus' },
      { level: 'thalamus', compartment: 'vpl' },
      { level: 'capsule', compartment: 'capsule_posterior_sensory' },
      { level: 'cortex', compartment: 'sensory_cortex' },
    ],
    serves: 'contralateral',
  },
  spinothalamic: {
    meta: {
      id: 'brain.spinothalamic',
      claim: 'The spinothalamic tract, already crossed in the cord, runs laterally in the medulla and dorsolaterally in the pons and midbrain to VPL, and on to the cortex.',
      sources: ['S58', 'S56'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [
      { level: 'medulla', compartment: 'spinothalamic' },
      { level: 'pons', compartment: 'spinothalamic' },
      { level: 'midbrain', compartment: 'spinothalamic' },
      { level: 'thalamus', compartment: 'vpl' },
      { level: 'capsule', compartment: 'capsule_posterior_sensory' },
      { level: 'cortex', compartment: 'sensory_cortex' },
    ],
    serves: 'contralateral',
  },
  faceNucleus: {
    meta: {
      id: 'brain.face-nucleus',
      claim: 'The spinal trigeminal nucleus and tract in the lateral medulla, and the principal sensory nucleus in the pontine tegmentum above it, carry sensation from the ipsilateral face.',
      sources: ['S60', 'S47', 'S58', 'S122', 'S115'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'medulla', compartment: 'spinal_trigeminal' }, { level: 'pons', compartment: 'trigeminal_sensory' }],
    serves: 'ipsilateral',
  },
  faceAscending: {
    meta: {
      id: 'brain.face-ascending',
      claim: 'Above the medulla facial sensation reaches VPM and the face area of the cortex on the opposite side; S60 also describes an ipsilateral projection.',
      sources: ['S55', 'S60', 'S66'],
      tier: 'T3',
      bookRef: p,
      conflict: 'C16',
    },
    steps: [{ level: 'thalamus', compartment: 'vpm' }, { level: 'capsule', compartment: 'capsule_posterior_sensory' }, { level: 'cortex', compartment: 'sensory_cortex' }],
    serves: 'contralateral',
  },
  corticobulbarFace: {
    meta: {
      id: 'brain.corticobulbar-face',
      claim: 'Corticobulbar fibres from the lateral motor cortex run through the genu, the peduncle and the basis pontis to the facial nucleus of the opposite side, for the lower face.',
      sources: ['S51', 'S54', 'S56'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'cortex', compartment: 'motor_cortex' }, { level: 'capsule', compartment: 'capsule_genu' }, { level: 'midbrain', compartment: 'peduncle' }, { level: 'pons', compartment: 'basis' }],
    serves: 'contralateral',
  },
  upperFaceBilateral: {
    meta: {
      id: 'brain.upper-face-bilateral',
      claim: 'The upper-face part of the facial nucleus receives both hemispheres, so a one-sided supranuclear lesion spares the forehead.',
      sources: ['S51'],
      tier: 'T2',
      bookRef: p,
    },
    bilateral: true,
  },
  corticobulbarTongue: {
    meta: {
      id: 'brain.corticobulbar-tongue',
      claim: 'Supranuclear control of the hypoglossal nucleus is predominantly crossed, so a supranuclear lesion weakens the opposite half of the tongue.',
      sources: ['S63', 'S54'],
      tier: 'T2',
      bookRef: p,
      pendingSource: 'R25: no source read says the tongue fibres run in the pyramid to the medulla; they are drawn with the corticobulbar tract',
    },
    steps: [{ level: 'cortex', compartment: 'motor_cortex' }, { level: 'capsule', compartment: 'capsule_genu' }, { level: 'midbrain', compartment: 'peduncle' }, { level: 'pons', compartment: 'basis' }, { level: 'medulla', compartment: 'pyramid' }],
    serves: 'contralateral',
  },
  corticobulbarPalate: {
    meta: {
      id: 'brain.corticobulbar-palate',
      claim: 'The nucleus ambiguus has predominantly bilateral supranuclear control; a one-sided supranuclear lesion gives at most a milder weakness.',
      sources: ['S64', 'S54'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'cortex', compartment: 'motor_cortex' }, { level: 'capsule', compartment: 'capsule_genu' }, { level: 'midbrain', compartment: 'peduncle' }, { level: 'pons', compartment: 'basis' }],
    bilateral: true,
  },
  facialNucleus: {
    meta: {
      id: 'brain.facial-nucleus',
      claim: 'A lesion of the facial nucleus or its fascicle in the pons paralyses the whole face on the same side.',
      sources: ['S51', 'S49', 'S59'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'pons', compartment: 'facial' }],
    serves: 'ipsilateral',
  },
  hypoglossal: {
    meta: {
      id: 'brain.hypoglossal',
      claim: 'A lesion of the hypoglossal nucleus or fascicles in the medulla weakens the same side of the tongue.',
      sources: ['S63', 'S48'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'medulla', compartment: 'hypoglossal' }],
    serves: 'ipsilateral',
  },
  ambiguus: {
    meta: {
      id: 'brain.ambiguus',
      claim: 'A lesion of the nucleus ambiguus weakens the palate, pharynx and larynx on the same side.',
      sources: ['S64', 'S47'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'medulla', compartment: 'ambiguus' }],
    serves: 'ipsilateral',
  },
  oculomotor: {
    meta: {
      id: 'brain.oculomotor',
      claim: 'A lesion of the oculomotor fascicles or nucleus in the midbrain gives a third nerve palsy on the same side. A nuclear lesion also gives ptosis on both sides or neither (C29) and weakens the opposite superior rectus (P9).',
      sources: ['S62', 'S50', 'S70'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'oculomotor' }, { level: 'midbrain', compartment: 'oculomotor_nucleus' }],
    serves: 'ipsilateral',
  },
  adduction: {
    meta: {
      id: 'brain.adduction',
      claim: 'The medial longitudinal fasciculus carries the abducens interneurons to the other side’s medial rectus, so a lesion of it loses adduction of the eye on its own side: an internuclear ophthalmoplegia. The third nerve moves the same muscle, so its fascicles and nucleus lose adduction too.',
      sources: ['S98', 'S61', 'S62'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [
      { level: 'pons', compartment: 'mlf' },
      { level: 'midbrain', compartment: 'mlf' },
      { level: 'midbrain', compartment: 'oculomotor' },
      { level: 'midbrain', compartment: 'oculomotor_nucleus' },
    ],
    serves: 'ipsilateral',
  },
  adductionGaze: {
    meta: {
      id: 'brain.adduction-gaze',
      claim: 'The abducens nucleus holds the interneurons for the other eye’s medial rectus, so a gaze palsy from the nucleus or the paramedian pontine reticular formation also loses adduction of the eye on the far side: the gaze is conjugate.',
      sources: ['S61', 'S99'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'pons', compartment: 'abducens_nucleus' }, { level: 'pons', compartment: 'pprf' }],
    serves: 'contralateral',
  },
  abductingNystagmus: {
    meta: {
      id: 'brain.abducting-nystagmus',
      claim: 'In an internuclear ophthalmoplegia the abducting eye — the one opposite the lesion — may show a dissociated horizontal nystagmus.',
      sources: ['S98'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'pons', compartment: 'mlf' }, { level: 'midbrain', compartment: 'mlf' }],
    serves: 'contralateral',
  },
  ptosis: {
    meta: {
      id: 'brain.ptosis',
      claim: 'A third nerve palsy from the fascicles droops the lid on its own side. From the nucleus it is left unsettled: one central caudal nucleus serves both lids, so a nuclear lesion gives ptosis on both sides or on neither.',
      sources: ['S62', 'S70'],
      tier: 'T3',
      bookRef: p,
      conflict: 'C29',
    },
    steps: [{ level: 'midbrain', compartment: 'oculomotor' }],
    serves: 'ipsilateral',
  },
  ptosisNuclear: {
    meta: {
      id: 'brain.ptosis-nuclear',
      claim: 'One central caudal nucleus raises both lids, so a lesion of the oculomotor nucleus gives ptosis on both sides or on neither; the model leaves it unsettled rather than choosing (C29).',
      sources: ['S70'],
      tier: 'T3',
      bookRef: p,
      conflict: 'C29',
    },
    steps: [{ level: 'midbrain', compartment: 'oculomotor_nucleus' }],
    bilateral: true,
  },
  elevation: {
    meta: {
      id: 'brain.elevation',
      claim: 'The superior rectus is weak on the side of an oculomotor fascicle lesion; a nuclear lesion weakens it on both sides, because the superior rectus subnuclei serve the opposite eye.',
      sources: ['S70'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'oculomotor' }, { level: 'midbrain', compartment: 'oculomotor_nucleus' }],
    serves: 'ipsilateral',
  },
  elevationCrossed: {
    meta: {
      id: 'brain.elevation-crossed',
      claim: 'The superior rectus subnuclei serve the opposite eye, so an oculomotor nucleus lesion weakens elevation of the other eye too.',
      sources: ['S70'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'oculomotor_nucleus' }],
    serves: 'contralateral',
  },
  abduction: {
    meta: {
      id: 'brain.abduction',
      claim: 'A lesion of the abducens nucleus or fascicle, or of the paramedian pontine reticular formation, weakens abduction of the eye on the same side.',
      sources: ['S61', 'S49', 'S99'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [
      { level: 'pons', compartment: 'abducens_nucleus' },
      { level: 'pons', compartment: 'abducens_fascicle' },
      { level: 'pons', compartment: 'pprf' },
    ],
    serves: 'ipsilateral',
  },
  gaze: {
    meta: {
      id: 'brain.gaze',
      claim: 'A lesion of the abducens nucleus, or of the paramedian pontine reticular formation beside it, gives a horizontal gaze palsy toward its own side; a fascicle lesion does not.',
      sources: ['S61', 'S99'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'pons', compartment: 'abducens_nucleus' }, { level: 'pons', compartment: 'pprf' }],
    serves: 'ipsilateral',
  },
  sympathetic: {
    meta: {
      id: 'brain.sympathetic',
      claim: 'First-order sympathetic fibres descend uncrossed through the midbrain, pons and lateral medulla; a lesion there gives an ipsilateral Horner syndrome.',
      sources: ['S16', 'S47'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'sympathetic' }, { level: 'pons', compartment: 'sympathetic' }, { level: 'medulla', compartment: 'sympathetic' }],
    serves: 'ipsilateral',
  },
  ataxia: {
    meta: {
      id: 'brain.ataxia',
      claim: 'A lesion of the inferior cerebellar peduncle gives ipsilateral limb ataxia, the pontine peduncle drawn with it; so does a lesion of the cerebellar hemisphere, which controls the same side of the body.',
      sources: ['S47', 'S65', 'S109', 'S110'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [
      { level: 'pons', compartment: 'cerebellar_peduncle' },
      { level: 'medulla', compartment: 'cerebellar_peduncle' },
      { level: 'cerebellum', compartment: 'cerebellar_hemisphere' },
    ],
    serves: 'ipsilateral',
  },
  vertigo: {
    meta: {
      id: 'brain.vertigo',
      claim: 'A lesion of the vestibular nuclei, in the medulla and inferior pons, gives vertigo and nystagmus.',
      sources: ['S47', 'S59'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'pons', compartment: 'vestibular' }, { level: 'medulla', compartment: 'vestibular' }],
  },
  gazeCortex: {
    meta: {
      id: 'brain.gaze-cortex',
      claim: 'A lesion of the frontal eye field (Brodmann area 8) loses gaze to the opposite side, so the eyes deviate toward the lesion; brainstem gaze palsies are instead on the side of the lesion. The deviation is brief: gone within 48 hours in 57% and within five days in 90% (C49, C50).',
      sources: ['S129', 'S130', 'S131'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'cortex', compartment: 'frontal_eye_field' }],
    serves: 'contralateral',
    course: { hyperacute: 'present', acute: 'indeterminate', subacute: 'indeterminate', chronic: 'absent' },
  },
  gerstmann: {
    meta: {
      id: 'brain.gerstmann',
      claim: 'Damage to the dominant inferior parietal lobule, at the angular gyrus, gives Gerstmann syndrome — finger agnosia, acalculia, agraphia and left–right disorientation, usually two or three of them, the complete tetrad rare (C51) — and it often comes with aphasia.',
      sources: ['S128', 'S129', 'S107'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'cortex', compartment: 'inferior_parietal' }],
  },
  ballismus: {
    meta: {
      id: 'brain.ballismus',
      claim: 'A lesion of the subthalamic nucleus gives hemiballismus — flinging, involuntary movements of the arm and leg — on the opposite side; stroke is its commonest cause. Lesions elsewhere in the basal ganglia can also give it (C47).',
      sources: ['S125', 'S126'],
      tier: 'T3',
      bookRef: p,
      conflict: 'C47',
    },
    steps: [{ level: 'thalamus', compartment: 'subthalamic' }],
    serves: 'contralateral',
  },
  trochlear: {
    meta: {
      id: 'brain.trochlear',
      claim: 'The trochlear fibres cross before they leave the dorsal midbrain, so a lesion of one trochlear nucleus weakens the superior oblique of the other eye: it rides high, worse looking down. One source states the crossing (C46).',
      sources: ['S120', 'S124'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'trochlear_nucleus' }],
    serves: 'contralateral',
  },
  jaw: {
    meta: {
      id: 'brain.jaw',
      claim: 'The trigeminal motor nucleus in the pontine tegmentum supplies the muscles of mastication; when one side is weak the jaw deviates toward it on opening, pushed by the other side’s pterygoids.',
      sources: ['S121', 'S122', 'S123'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'pons', compartment: 'trigeminal_motor' }],
    serves: 'ipsilateral',
  },
  hearing: {
    meta: {
      id: 'brain.hearing',
      claim: 'The AICA supplies the lateral pons with the cochlear nuclei of the eighth nerve, and gives the labyrinthine artery; a lesion there loses hearing on its own side.',
      sources: ['S113', 'S114', 'S65', 'S115'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'pons', compartment: 'cochlear' }],
    serves: 'ipsilateral',
  },
  upgaze: {
    meta: {
      id: 'brain.upgaze',
      claim: 'Compression of the rostral midbrain and pretectum at the level of the superior colliculus, where the vertical gaze centres lie, limits conjugate upgaze; downgaze is classically preserved (C42).',
      sources: ['S116', 'S119'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'pretectum' }],
  },
  lightNear: {
    meta: {
      id: 'brain.light-near',
      claim: 'The light-reflex fibres end in the pretectal nucleus, which signals both Edinger–Westphal nuclei; damage there leaves the pupils poorly reactive to light but constricting to near — light–near dissociation.',
      sources: ['S116', 'S117', 'S118'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'pretectum' }],
  },
  convergenceRetraction: {
    meta: {
      id: 'brain.convergence-retraction',
      claim: 'A dorsal midbrain lesion gives convergence–retraction nystagmus: jerky convergence and retraction of both eyes, especially on attempted upgaze.',
      sources: ['S116'],
      tier: 'T2',
      bookRef: p,
    },
    steps: [{ level: 'midbrain', compartment: 'pretectum' }],
  },
  truncalAtaxia: {
    meta: {
      id: 'brain.truncal-ataxia',
      claim: 'A lesion of the vermis gives truncal and gait ataxia with the limbs spared: the vermis coordinates the trunk.',
      sources: ['S109', 'S110'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [{ level: 'cerebellum', compartment: 'vermis' }],
  },
  truncalAfterHemisphere: {
    meta: {
      id: 'brain.truncal-after-hemisphere',
      claim: 'Hemispheric cerebellar lesions give mainly incoordination and midline lesions imbalance, so after a hemisphere lesion truncal ataxia is left unsettled rather than absent (C35).',
      sources: ['S111', 'S109'],
      tier: 'T3',
      bookRef: p,
      conflict: 'C35',
    },
    steps: [{ level: 'cerebellum', compartment: 'cerebellar_hemisphere' }],
    state: 'indeterminate',
  },
  dominance: {
    meta: {
      id: 'brain.dominance',
      claim: 'The dominant hemisphere for language is the left in most people. How often it is not rises with left-handedness — about 4% of strong right-handers, 15% of the ambidextrous and 27% of strong left-handers — and the model states the usual case rather than modelling handedness.',
      sources: ['S107', 'S108'],
      tier: 'T1',
      bookRef: p,
    },
    language: 'L',
  },
  fluency: {
    meta: {
      id: 'brain.fluency',
      claim: 'Broca area, in the inferior frontal gyrus of the dominant hemisphere (Brodmann 44 and 45), is where a lesion makes speech non-fluent. So does the anterior border zone around it, between the anterior and middle cerebral arteries, which spares and isolates it (P21).',
      sources: ['S100', 'S103', 'S107', 'S142'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [
      { level: 'cortex', compartment: 'inferior_frontal' },
      { level: 'cortex', compartment: 'anterior_borderzone' },
    ],
  },
  comprehension: {
    meta: {
      id: 'brain.comprehension',
      claim: 'Wernicke area, in the posterior superior temporal gyrus of the dominant hemisphere, is where a lesion impairs comprehension. S102 says a lesion of the same gyrus may instead give conduction aphasia, with comprehension kept (C34). The posterior border zone around it, between the middle and posterior cerebral arteries, also impairs comprehension while sparing and isolating it (P21).',
      sources: ['S101', 'S102', 'S107', 'S103', 'S142'],
      tier: 'T3',
      bookRef: p,
      conflict: 'C34',
    },
    steps: [
      { level: 'cortex', compartment: 'superior_temporal' },
      { level: 'cortex', compartment: 'posterior_borderzone' },
    ],
  },
  repetition: {
    meta: {
      id: 'brain.repetition',
      claim: 'Repetition fails after a dominant lesion of Broca area, of Wernicke area, or of the inferior parietal lobule between them — the last alone being conduction aphasia. A border-zone lesion around them spares it: the transcortical aphasias (P21).',
      sources: ['S100', 'S101', 'S102', 'S103'],
      tier: 'T1',
      bookRef: p,
    },
    steps: [
      { level: 'cortex', compartment: 'inferior_frontal' },
      { level: 'cortex', compartment: 'superior_temporal' },
      { level: 'cortex', compartment: 'inferior_parietal' },
    ],
  },
  neglect: {
    meta: {
      id: 'brain.neglect',
      claim: 'A lesion of the nondominant posterior parietal cortex gives neglect of the opposite side of space. After a dominant lesion it is rarer and less lasting (about 5% against 17% at twelve weeks), so the model leaves it unsettled rather than absent (C32).',
      sources: ['S106', 'S107'],
      tier: 'T3',
      bookRef: p,
      conflict: 'C32',
    },
    steps: [{ level: 'cortex', compartment: 'inferior_parietal' }],
    afterDominant: 'indeterminate',
  },
  partsAt: {
    meta: {
      id: 'brain.parts-at',
      claim: 'The motor and sensory cortex, with the inferior frontal, superior temporal and inferior parietal cortex around the Sylvian fissure and the frontal eye field in front of the motor strip; the genu and posterior limb of the capsule; VPL and VPM, with the subthalamic nucleus below them; in the midbrain the peduncle, oculomotor fascicles, lemniscus, spinothalamic tract and sympathetic fibres; in the midbrain also the oculomotor nucleus, the medial longitudinal fasciculus dorsally at the superior colliculus the pretectum and at the inferior colliculus the trochlear nucleus; in the pons the basis, facial and abducens nuclei and fascicles, the paramedian pontine reticular formation, the medial longitudinal fasciculus, lemniscus, spinothalamic tract, sympathetic fibres, cerebellar peduncle and vestibular nuclei; the cochlear nuclei and the trigeminal motor and principal sensory nuclei in the lateral pons, and the cerebellar hemispheres and vermis behind the pons and medulla; in the medulla the pyramid, lemniscus, hypoglossal nucleus, spinothalamic tract, spinal trigeminal nucleus, sympathetic fibres, nucleus ambiguus, cerebellar peduncle and vestibular nuclei.',
      sources: ['S54', 'S56', 'S57', 'S58', 'S59', 'S16', 'S47', 'S48', 'S98', 'S99', 'S70', 'S104', 'S105', 'S110', 'S114', 'S116', 'S120', 'S122', 'S125', 'S130'],
      tier: 'T1',
      bookRef: p,
    },
    parts: {
      cortex: ['motor_cortex', 'sensory_cortex', 'inferior_frontal', 'superior_temporal', 'inferior_parietal', 'frontal_eye_field', 'anterior_borderzone', 'posterior_borderzone'],
      capsule: ['capsule_genu', 'capsule_posterior_motor', 'capsule_posterior_sensory'],
      thalamus: ['vpl', 'vpm', 'subthalamic'],
      midbrain: ['peduncle', 'oculomotor', 'oculomotor_nucleus', 'mlf', 'pretectum', 'trochlear_nucleus', 'medial_lemniscus', 'spinothalamic', 'sympathetic'],
      pons: [
        'basis',
        'facial',
        'abducens_nucleus',
        'abducens_fascicle',
        'pprf',
        'mlf',
        'medial_lemniscus',
        'spinothalamic',
        'sympathetic',
        'cerebellar_peduncle',
        'vestibular',
        'cochlear',
        'trigeminal_motor',
        'trigeminal_sensory',
      ],
      medulla: [
        'pyramid',
        'medial_lemniscus',
        'hypoglossal',
        'spinothalamic',
        'spinal_trigeminal',
        'sympathetic',
        'ambiguus',
        'cerebellar_peduncle',
        'vestibular',
      ],
      cerebellum: ['cerebellar_hemisphere', 'vermis'],
    },
  },
  somatotopic: {
    meta: {
      id: 'brain.somatotopic',
      claim: 'The motor and sensory cortex and the posterior limb of the capsule are laid out by body region.',
      sources: ['S54', 'S66', 'S56'],
      tier: 'T1',
      bookRef: p,
    },
    compartments: ['motor_cortex', 'sensory_cortex', 'capsule_posterior_motor', 'capsule_posterior_sensory'],
  },
  limbRegions: {
    meta: {
      id: 'brain.limb-regions',
      claim: 'The arm is C5–T1 and the leg L2 downward, the genitals and perineum represented with the leg.',
      sources: ['S66', 'S31'],
      tier: 'T2',
      bookRef: p,
    },
    arm: ['C5', 'T1'],
    leg: ['L2', 'Co1'],
  },
  axialRegions: {
    meta: {
      id: 'brain.axial-regions',
      claim: 'The neck is C1–C4 and the trunk T2–L1, represented between arm and leg.',
      sources: ['S66'],
      tier: 'T2',
      bookRef: p,
      pendingSource: 'R20: the segment boundaries of neck and trunk are a convention',
    },
    neck: ['C1', 'C4'],
    trunk: ['T2', 'L1'],
  },
  territories: {
    lateral_medullary: {
      meta: {
        id: 'territory.lateral-medullary',
        claim: 'The lateral medulla (PICA or vertebral artery) holds the spinothalamic tract, the spinal trigeminal nucleus, the descending sympathetic fibres, the nucleus ambiguus, the inferior cerebellar peduncle and the vestibular nuclei.',
        sources: ['S47', 'S65', 'S64'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'medulla',
      compartments: ['spinothalamic', 'spinal_trigeminal', 'sympathetic', 'ambiguus', 'cerebellar_peduncle', 'vestibular'],
    },
    medial_medullary: {
      meta: {
        id: 'territory.medial-medullary',
        claim: 'The medial medulla holds the pyramid, the medial lemniscus and the hypoglossal nucleus and fascicles.',
        sources: ['S48', 'S65'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'medulla',
      compartments: ['pyramid', 'medial_lemniscus', 'hypoglossal'],
    },
    ventral_pons: {
      meta: {
        id: 'territory.ventral-pons',
        claim: 'The ventral pons holds the basis pontis and the facial and abducens fascicles.',
        sources: ['S49', 'S61'],
        tier: 'T3',
        bookRef: p,
        conflict: 'C17',
      },
      level: 'pons',
      compartments: ['basis', 'facial', 'abducens_fascicle'],
    },
    ventral_pons_bilateral: {
      meta: {
        id: 'territory.ventral-pons-bilateral',
        claim: 'Occlusion of the proximal and middle basilar artery takes the ventral pons on both sides and spares the tegmentum: locked-in syndrome — quadriplegia and anarthria, the face, tongue and palate weak on both sides, lateral gaze lost, with consciousness, hearing, comprehension and vertical eye movement kept (C52, C53, C54).',
        sources: ['S132', 'S133', 'S134'],
        tier: 'T3',
        bookRef: p,
        conflict: 'C52',
      },
      level: 'pons',
      compartments: ['basis', 'facial', 'abducens_fascicle'],
      midline: true,
    },
    dorsal_pons: {
      meta: {
        id: 'territory.dorsal-pons',
        claim: 'The dorsal pons holds the abducens nucleus wrapped by the facial genu.',
        sources: ['S61', 'S59'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'pons',
      compartments: ['abducens_nucleus', 'facial'],
    },
    midbrain_peduncle: {
      meta: {
        id: 'territory.midbrain-peduncle',
        claim: 'Weber syndrome takes the cerebral peduncle and the oculomotor fascicles.',
        sources: ['S50', 'S62', 'S65'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'midbrain',
      compartments: ['peduncle', 'oculomotor'],
    },
    internal_capsule: {
      meta: {
        id: 'territory.internal-capsule',
        claim: 'A pure motor lacune takes the corticobulbar and corticospinal fibres of the genu and posterior limb.',
        sources: ['S55', 'S56'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'capsule',
      compartments: ['capsule_genu', 'capsule_posterior_motor'],
    },
    thalamus: {
      meta: {
        id: 'territory.thalamus',
        claim: 'A pure sensory lacune takes the lateral thalamus, VPL and VPM.',
        sources: ['S55', 'S57', 'S60'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'thalamus',
      compartments: ['vpl', 'vpm'],
    },
    mca_cortex: {
      meta: {
        id: 'territory.mca-cortex',
        claim: 'The superior MCA division supplies the lateral motor and sensory cortex — face and arm — and, through its precentral branch, Brodmann 44 and 45: Broca area.',
        sources: ['S54', 'S66', 'S104', 'S105'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'cortex',
      compartments: ['motor_cortex', 'sensory_cortex', 'inferior_frontal'],
      regions: ['face', 'arm'],
    },
    mca_inferior: {
      meta: {
        id: 'territory.mca-inferior',
        claim: 'The inferior MCA division supplies the lateral temporal lobe and the angular and supramarginal gyri; a stroke of it frequently gives a contralateral homonymous hemianopia (C31) and generally no weakness.',
        sources: ['S104', 'S105', 'S101'],
        tier: 'T3',
        bookRef: p,
        conflict: 'C31',
      },
      level: 'cortex',
      compartments: ['superior_temporal', 'inferior_parietal'],
      vision: ['meyer_loop', 'parietal_radiation'],
    },
    mca_whole: {
      meta: {
        id: 'territory.mca-whole',
        claim: 'Both divisions of the MCA: the lateral motor and sensory cortex, the peri-Sylvian language cortex, the frontal eye field and the optic radiation — in the dominant hemisphere, global aphasia; on the first day, forced gaze deviation.',
        sources: ['S103', 'S104', 'S105', 'S131'],
        tier: 'T3',
        bookRef: p,
        conflict: 'C31',
      },
      level: 'cortex',
      compartments: ['motor_cortex', 'sensory_cortex', 'inferior_frontal', 'superior_temporal', 'inferior_parietal', 'frontal_eye_field'],
      regions: ['face', 'arm'],
      vision: ['meyer_loop', 'parietal_radiation'],
    },
    broca_area: {
      meta: {
        id: 'territory.broca-area',
        claim: 'The inferior frontal gyrus alone: in the dominant hemisphere, pure Broca aphasia.',
        sources: ['S100', 'S107'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'cortex',
      compartments: ['inferior_frontal'],
    },
    wernicke_area: {
      meta: {
        id: 'territory.wernicke-area',
        claim: 'The posterior superior temporal gyrus alone: in the dominant hemisphere, Wernicke aphasia (C34).',
        sources: ['S101', 'S107', 'S102'],
        tier: 'T3',
        bookRef: p,
        conflict: 'C34',
      },
      level: 'cortex',
      compartments: ['superior_temporal'],
    },
    supramarginal: {
      meta: {
        id: 'territory.supramarginal',
        claim: 'The inferior parietal lobule (supramarginal and angular gyri): conduction aphasia in the dominant hemisphere, neglect of the other side of space in the nondominant one.',
        sources: ['S102', 'S106', 'S107'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'cortex',
      compartments: ['inferior_parietal'],
    },
    cerebellar_hemisphere: {
      meta: {
        id: 'territory.cerebellar-hemisphere',
        claim: 'A lesion of one cerebellar hemisphere gives limb ataxia on the same side.',
        sources: ['S109', 'S110'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'cerebellum',
      compartments: ['cerebellar_hemisphere'],
    },
    vermis: {
      meta: {
        id: 'territory.vermis',
        claim: 'A lesion of the vermis, a midline structure, gives truncal and gait ataxia with the limbs spared.',
        sources: ['S109', 'S110'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'cerebellum',
      compartments: ['vermis'],
      midline: true,
    },
    aica: {
      meta: {
        id: 'territory.aica',
        claim: 'The anterior inferior cerebellar artery supplies the lateral pons — the facial nucleus, the cochlear and vestibular nuclei, the spinothalamic tract, the descending sympathetic fibres and the cerebellar peduncle — and the ear through its labyrinthine branch. Whether the corticospinal tract and lemniscus belong to it is disputed (C37).',
        sources: ['S113', 'S114', 'S65'],
        tier: 'T3',
        bookRef: p,
        conflict: 'C37',
      },
      level: 'pons',
      compartments: ['facial', 'cochlear', 'vestibular', 'spinothalamic', 'sympathetic', 'cerebellar_peduncle'],
    },
    pica: {
      meta: {
        id: 'territory.pica',
        claim: 'The posterior inferior cerebellar artery supplies the lateral medulla and the inferior vermis and undersurface of the cerebellar hemisphere; it may spare either, and the medulla alone stays as its own place (C38).',
        sources: ['S110', 'S113', 'S114', 'S47'],
        tier: 'T3',
        bookRef: p,
        conflict: 'C38',
      },
      level: 'medulla',
      compartments: ['spinothalamic', 'spinal_trigeminal', 'sympathetic', 'ambiguus', 'cerebellar_peduncle', 'vestibular'],
      also: [{ level: 'cerebellum', compartments: ['cerebellar_hemisphere', 'vermis'] }],
    },
    sca: {
      meta: {
        id: 'territory.sca',
        claim: 'The superior cerebellar artery supplies the superior vermis and the superior cortex of the hemisphere. Its midbrain branches are not modelled.',
        sources: ['S110', 'S113', 'S114'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'cerebellum',
      compartments: ['cerebellar_hemisphere', 'vermis'],
    },
    aca_cortex: {
      meta: {
        id: 'territory.aca-cortex',
        claim: 'The ACA supplies the medial motor and sensory cortex: the leg.',
        sources: ['S54', 'S66', 'S53'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'cortex',
      compartments: ['motor_cortex', 'sensory_cortex'],
      regions: ['leg'],
    },
    mlf_pons: {
      meta: {
        id: 'territory.mlf-pons',
        claim: 'A lesion of the medial longitudinal fasciculus alone, in the pons, is an internuclear ophthalmoplegia and nothing else.',
        sources: ['S98'],
        tier: 'T2',
        bookRef: p,
      },
      level: 'pons',
      compartments: ['mlf'],
    },
    pontine_tegmentum: {
      meta: {
        id: 'territory.pontine-tegmentum',
        claim: 'A lesion of the pontine tegmentum taking the abducens nucleus (or the paramedian pontine reticular formation) and the neighbouring medial longitudinal fasciculus is one-and-a-half syndrome: a gaze palsy toward that side with an internuclear ophthalmoplegia, leaving only the other eye’s abduction.',
        sources: ['S99', 'S61'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'pons',
      compartments: ['abducens_nucleus', 'mlf'],
    },
    oculomotor_nucleus: {
      meta: {
        id: 'territory.oculomotor-nucleus',
        claim: 'A lesion of the oculomotor nucleus itself gives a third nerve palsy on its own side with the other eye’s superior rectus weak, and ptosis on both sides or on neither.',
        sources: ['S70'],
        tier: 'T2',
        bookRef: p,
      },
      level: 'midbrain',
      compartments: ['oculomotor_nucleus'],
    },
    dorsal_midbrain: {
      meta: {
        id: 'territory.dorsal-midbrain',
        claim: 'Compression of the dorsal midbrain — the pretectum at the superior colliculus, as from a pineal tumour or hydrocephalus — gives Parinaud syndrome: upgaze palsy, convergence–retraction nystagmus and light–near dissociation. It takes both sides (C43).',
        sources: ['S116', 'S119'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'midbrain',
      compartments: ['pretectum'],
      midline: true,
    },
    frontal_eye_field: {
      meta: {
        id: 'territory.frontal-eye-field',
        claim: 'A lesion of the frontal eye field alone: the eyes deviate toward it on the first day, and recover within days.',
        sources: ['S129', 'S130', 'S131'],
        tier: 'T2',
        bookRef: p,
      },
      level: 'cortex',
      compartments: ['frontal_eye_field'],
    },
    borderzone_anterior: {
      meta: {
        id: 'territory.borderzone-anterior',
        claim: 'The border zone between the anterior and middle cerebral arteries, around Broca area but sparing it: in the dominant hemisphere, transcortical motor aphasia — non-fluent, understands, repeats. S142 says it begins as the mixed form (C62).',
        sources: ['S103', 'S142'],
        tier: 'T2',
        bookRef: p,
      },
      level: 'cortex',
      compartments: ['anterior_borderzone'],
    },
    borderzone_posterior: {
      meta: {
        id: 'territory.borderzone-posterior',
        claim: 'The border zone between the middle and posterior cerebral arteries, around Wernicke area but sparing it: in the dominant hemisphere, transcortical sensory aphasia — fluent, does not understand, repeats. S142 says it begins as the mixed form (C62).',
        sources: ['S103', 'S142'],
        tier: 'T2',
        bookRef: p,
      },
      level: 'cortex',
      compartments: ['posterior_borderzone'],
    },
    subthalamic_nucleus: {
      meta: {
        id: 'territory.subthalamic-nucleus',
        claim: 'A lesion of one subthalamic nucleus, medial to the internal capsule and below the thalamus, gives hemiballismus of the opposite arm and leg.',
        sources: ['S125', 'S126'],
        tier: 'T1',
        bookRef: p,
      },
      level: 'thalamus',
      compartments: ['subthalamic'],
    },
    trochlear_nucleus: {
      meta: {
        id: 'territory.trochlear-nucleus',
        claim: 'A lesion of one trochlear nucleus, near the midline beside the MLF at the inferior colliculus, weakens the superior oblique of the other eye.',
        sources: ['S120', 'S124'],
        tier: 'T2',
        bookRef: p,
      },
      level: 'midbrain',
      compartments: ['trochlear_nucleus'],
    },
    midpontine_tegmentum: {
      meta: {
        id: 'territory.midpontine-tegmentum',
        claim: 'A lesion of the mid-pontine tegmentum takes the trigeminal motor and sensory nuclei, the spinothalamic tract, the medial lemniscus and the cerebellar peduncle: the jaw and face on one side, the body on the other, and ataxia on the side of the lesion.',
        sources: ['S115', 'S122'],
        tier: 'T2',
        bookRef: p,
      },
      level: 'pons',
      compartments: ['trigeminal_motor', 'trigeminal_sensory', 'spinothalamic', 'medial_lemniscus', 'cerebellar_peduncle'],
    },
  },
};
