// Registry of sources. Must match the table in docs/SOURCES.md exactly; a test compares
// ids, titles and links, so neither can drift from the other.
import type { SourceId } from './vocab.ts';

export const SOURCE_IDS: readonly SourceId[] = [
  'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'S12',
  'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19', 'S20', 'S21', 'S22', 'S23',
  'S24', 'S25', 'S26', 'S27', 'S28', 'S29', 'S30', 'S31', 'S32',
  'S33', 'S34', 'S35', 'S36', 'S37', 'S38', 'S39', 'S40', 'S41', 'S42', 'S43', 'S44', 'S45', 'S46',
  'S47', 'S48', 'S49', 'S50', 'S51', 'S52', 'S53', 'S54', 'S55', 'S56', 'S57', 'S58', 'S59', 'S60', 'S61', 'S62', 'S63', 'S64', 'S65', 'S66',
  'S67', 'S68', 'S69', 'S70',
  'S71', 'S72', 'S73', 'S74', 'S75', 'S76', 'S77', 'S78', 'S79', 'S80', 'S81', 'S82', 'S83', 'S84', 'S85', 'S86', 'S87', 'S88', 'S89', 'S90',
  'S91', 'S92', 'S93', 'S94', 'S95', 'S96', 'S97', 'S98', 'S99',
  'S100', 'S101', 'S102', 'S103', 'S104', 'S105', 'S106', 'S107', 'S108',
  'S109', 'S110', 'S111', 'S112',
  'S113', 'S114', 'S115',
  'S116', 'S117', 'S118', 'S119',
  'S120', 'S121', 'S122', 'S123', 'S124',
  'S125', 'S126', 'S127',
  'S128', 'S129', 'S130', 'S131', 'S132', 'S133', 'S134', 'S135', 'S136', 'S137', 'S138', 'S139',
];

export type SourceRecord = { readonly id: SourceId; readonly title: string; readonly url: string };

export const SOURCES: readonly SourceRecord[] = [
  { id: 'S01', title: 'StatPearls — Brown-Séquard Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK538135/' },
  { id: 'S02', title: 'StatPearls — Spinal Shock', url: 'https://www.ncbi.nlm.nih.gov/books/NBK448163/' },
  { id: 'S03', title: 'StatPearls — Neurogenic Shock', url: 'https://www.ncbi.nlm.nih.gov/books/NBK459361/' },
  { id: 'S04', title: 'StatPearls — Autonomic Dysreflexia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK482434/' },
  { id: 'S05', title: 'MSD Manual Professional — Table: Spinal Cord Syndromes', url: 'https://www.msdmanuals.com/professional/multimedia/table/spinal-cord-syndromes' },
  { id: 'S06', title: 'StatPearls — Central Cord Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK441932/' },
  { id: 'S07', title: 'StatPearls — Anterior Spinal Artery Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560731/' },
  { id: 'S08', title: 'StatPearls — Syringomyelia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537110/' },
  { id: 'S09', title: 'StatPearls — Cauda Equina and Conus Medullaris Syndromes', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537200/' },
  { id: 'S10', title: 'StatPearls — Spinal Cord Subacute Combined Degeneration', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560728/' },
  { id: 'S11', title: 'StatPearls — Neuroanatomy, Anterior White Commissure', url: 'https://www.ncbi.nlm.nih.gov/books/NBK546614/' },
  { id: 'S12', title: 'StatPearls — Deep Tendon Reflexes', url: 'https://www.ncbi.nlm.nih.gov/books/NBK531502/' },
  { id: 'S13', title: 'StatPearls — Tabes Dorsalis', url: 'https://www.ncbi.nlm.nih.gov/books/NBK557891/' },
  { id: 'S14', title: 'StatPearls — Neuroanatomy, Conus Medullaris', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545227/' },
  { id: 'S15', title: 'StatPearls — Spinal Cord Injuries', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560721/' },
  { id: 'S16', title: 'StatPearls — Horner Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK500000/' },
  { id: 'S17', title: 'StatPearls — Amyotrophic Lateral Sclerosis', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556151/' },
  { id: 'S18', title: 'StatPearls — Motor Neuron Disease', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560774/' },
  { id: 'S19', title: 'StatPearls — Cervical Radiculopathy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK441828/' },
  { id: 'S20', title: 'StatPearls — Neurogenic Bladder', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560617/' },
  { id: 'S21', title: 'StatPearls — Anatomy, Skin, Dermatomes', url: 'https://www.ncbi.nlm.nih.gov/books/NBK535401/' },
  { id: 'S22', title: 'StatPearls — Anatomy, Abdomen and Pelvis, Pudendal Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK554736/' },
  { id: 'S23', title: 'Brain Communications 2025 — The human spinothalamic tract: lessons from cordotomy', url: 'https://academic.oup.com/braincomms/article/7/3/fcaf237/8165923' },
  { id: 'S24', title: 'StatPearls — Neuroanatomy, Spinal Cord Morphology', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545206/' },
  { id: 'S25', title: 'StatPearls — Neuroanatomy, Touch Receptor', url: 'https://www.ncbi.nlm.nih.gov/books/NBK547731/' },
  { id: 'S26', title: 'Neuroscience Online (UTHealth) — Anatomy of the Spinal Cord, ch. 3', url: 'https://nba.uth.tmc.edu/neuroscience/m/s2/chapter03.html' },
  { id: 'S27', title: 'StatPearls — Neuroanatomy, Posterior Column', url: 'https://www.ncbi.nlm.nih.gov/books/NBK507888/' },
  { id: 'S28', title: 'StatPearls — Neuroanatomy, Unmyelinated Nerve Fibers', url: 'https://www.ncbi.nlm.nih.gov/books/NBK554461/' },
  { id: 'S29', title: 'Snooks & Swash, JNNP 1985 — Motor conduction velocity in the human spinal cord', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1028573/' },
  { id: 'S30', title: 'Radiopaedia — Spinal cord', url: 'https://radiopaedia.org/articles/spinal-cord' },
  { id: 'S31', title: 'StatPearls — Physiology, Spinal Cord', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544267/' },
  { id: 'S32', title: 'StatPearls — Cervical Injury', url: 'https://www.ncbi.nlm.nih.gov/books/NBK448146/' },
  { id: 'S33', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Brachial Plexus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK500016/' },
  { id: 'S34', title: 'StatPearls — Anatomy, Head and Neck: Brachial Plexus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK531473/' },
  { id: 'S35', title: 'StatPearls — Erb Palsy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK513260/' },
  { id: 'S36', title: 'StatPearls — Klumpke Palsy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK531500/' },
  { id: 'S37', title: 'StatPearls — Electrodiagnostic Evaluation of Brachial Plexopathies', url: 'https://www.ncbi.nlm.nih.gov/books/NBK562197/' },
  { id: 'S38', title: 'StatPearls — Ulnar Nerve Entrapment', url: 'https://www.ncbi.nlm.nih.gov/books/NBK555929/' },
  { id: 'S39', title: 'StatPearls — Wrist Drop', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532993/' },
  { id: 'S40', title: 'StatPearls — Radial Nerve Injury', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537304/' },
  { id: 'S41', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Median Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK448084/' },
  { id: 'S42', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Axillary Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK493212/' },
  { id: 'S43', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Musculocutaneous Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK534199/' },
  { id: 'S44', title: 'StatPearls — Anatomy, Thorax, Long Thoracic Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK535396/' },
  { id: 'S45', title: 'StatPearls — Anatomy, Medial Antebrachial Cutaneous Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK551638/' },
  { id: 'S46', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Cutaneous Innervation', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545249/' },
  { id: 'S47', title: 'StatPearls — Lateral Medullary Syndrome (Wallenberg Syndrome)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK551670/' },
  { id: 'S48', title: 'StatPearls — Medial Medullary Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560590/' },
  { id: 'S49', title: 'StatPearls — Millard-Gubler Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532907/' },
  { id: 'S50', title: 'StatPearls — Weber Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK559158/' },
  { id: 'S51', title: 'StatPearls — Neuroanatomy, Cranial Nerve 7 (Facial)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526119/' },
  { id: 'S52', title: 'StatPearls — Middle Cerebral Artery Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556132/' },
  { id: 'S53', title: 'StatPearls — Anterior Cerebral Artery Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537333/' },
  { id: 'S54', title: 'StatPearls — Neuroanatomy, Precentral Gyrus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544218/' },
  { id: 'S55', title: 'StatPearls — Lacunar Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK563216/' },
  { id: 'S56', title: 'StatPearls — Neuroanatomy, Internal Capsule', url: 'https://www.ncbi.nlm.nih.gov/books/NBK542181/' },
  { id: 'S57', title: 'StatPearls — Neuroanatomy, Medial Lemniscus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526040/' },
  { id: 'S58', title: 'StatPearls — Neuroanatomy, Spinothalamic Tract', url: 'https://www.ncbi.nlm.nih.gov/books/NBK507824/' },
  { id: 'S59', title: 'StatPearls — Neuroanatomy, Brainstem', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544297/' },
  { id: 'S60', title: 'StatPearls — Neuroanatomy, Spinal Trigeminal Nucleus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK539729/' },
  { id: 'S61', title: 'StatPearls — Neuroanatomy, Abducens Nucleus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544265/' },
  { id: 'S62', title: 'StatPearls — Cranial Nerve III Palsy (Oculomotor Palsy)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526112/' },
  { id: 'S63', title: 'StatPearls — Neuroanatomy, Cranial Nerve 12 (Hypoglossal)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532869/' },
  { id: 'S64', title: 'StatPearls — Neuroanatomy, Nucleus Ambiguus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK547744/' },
  { id: 'S65', title: 'StatPearls — Brainstem Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560896/' },
  { id: 'S66', title: 'StatPearls — Neurosurgery, Sensory Homunculus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK549841/' },
  { id: 'S67', title: 'StatPearls — Romberg Test', url: 'https://www.ncbi.nlm.nih.gov/books/NBK563187/' },
  { id: 'S68', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Hand Interossei Muscles', url: 'https://www.ncbi.nlm.nih.gov/books/NBK534772/' },
  { id: 'S69', title: 'StatPearls — Neuroanatomy, White Rami Communicans', url: 'https://www.ncbi.nlm.nih.gov/books/NBK549910/' },
  { id: 'S70', title: 'Cornblath — Diplopia Due to Ocular Motor Cranial Neuropathies (Continuum, 2014)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10563973/' },
  { id: 'S71', title: 'StatPearls — Anatomy, Back, Lumbar Plexus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545137/' },
  { id: 'S72', title: 'StatPearls — Lumbosacral Plexopathy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556030/' },
  { id: 'S73', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Thigh Nerves', url: 'https://www.ncbi.nlm.nih.gov/books/NBK482225/' },
  { id: 'S74', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Lateral Femoral Cutaneous Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532301/' },
  { id: 'S75', title: 'StatPearls — Anatomy, Sciatic Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK482431/' },
  { id: 'S76', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Calf Common Peroneal Nerve (Common Fibular Nerve)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532968/' },
  { id: 'S77', title: 'StatPearls — Peroneal Nerve Injury', url: 'https://www.ncbi.nlm.nih.gov/books/NBK549859/' },
  { id: 'S78', title: 'StatPearls — Foot Drop', url: 'https://www.ncbi.nlm.nih.gov/books/NBK554393/' },
  { id: 'S79', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Tibial Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537028/' },
  { id: 'S80', title: 'StatPearls — Anatomy, Abdomen and Pelvis: Superior Gluteal Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK535408/' },
  { id: 'S81', title: 'StatPearls — Anatomy, Abdomen and Pelvis: Inferior Gluteal Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532884/' },
  { id: 'S82', title: 'StatPearls — Lumbosacral Radiculopathy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK430837/' },
  { id: 'S83', title: 'StatPearls — Electrodiagnostic Evaluation of Peroneal Neuropathy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK563251/' },
  { id: 'S84', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Tibialis Posterior Muscle', url: 'https://www.ncbi.nlm.nih.gov/books/NBK539913/' },
  { id: 'S85', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Iliopsoas Muscle', url: 'https://www.ncbi.nlm.nih.gov/books/NBK531508/' },
  { id: 'S86', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Saphenous Nerve, Artery, and Vein', url: 'https://www.ncbi.nlm.nih.gov/books/NBK541045/' },
  { id: 'S87', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Sural Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK546638/' },
  { id: 'S88', title: 'StatPearls — Electrodiagnostic Evaluation of Lumbosacral Radiculopathy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK563224/' },
  { id: 'S89', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Thigh Femoral Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556065/' },
  { id: 'S90', title: 'Stamiris et al. — S1 Radiculopathy Initially Presenting With Sole Knee Flexion Weakness (Cureus, 2024)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11070185/' },
  { id: 'S91', title: 'StatPearls — Neuroanatomy, Visual Pathway', url: 'https://www.ncbi.nlm.nih.gov/books/NBK553189/' },
  { id: 'S92', title: 'StatPearls — Hemianopsia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK562262/' },
  { id: 'S93', title: 'StatPearls — Homonymous Superior Quadrantanopia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK558982/' },
  { id: 'S94', title: 'StatPearls — Posterior Cerebral Artery Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532296/' },
  { id: 'S95', title: 'StatPearls — Marcus Gunn Pupil', url: 'https://www.ncbi.nlm.nih.gov/books/NBK557675/' },
  { id: 'S96', title: 'StatPearls — Neuroanatomy, Bitemporal Hemianopsia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545213/' },
  { id: 'S97', title: 'StatPearls — Homonymous Hemianopsia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK558929/' },
  { id: 'S98', title: 'StatPearls — Internuclear Ophthalmoplegia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK441970/' },
  { id: 'S99', title: 'Xue et al. — One-and-a-half syndrome with its spectrum disorders (Quant Imaging Med Surg, 2017)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5756788/' },
  { id: 'S100', title: 'StatPearls — Broca Aphasia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK436010/' },
  { id: 'S101', title: 'StatPearls — Wernicke Aphasia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK441951/' },
  { id: 'S102', title: 'StatPearls — Conduction Aphasia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537006/' },
  { id: 'S103', title: 'StatPearls — Aphasia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK559315/' },
  { id: 'S104', title: 'StatPearls — Middle Cerebral Artery Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556132/' },
  { id: 'S105', title: 'StatPearls — Neuroanatomy, Middle Cerebral Artery', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526002/' },
  { id: 'S106', title: 'StatPearls — Spatial Neglect', url: 'https://www.ncbi.nlm.nih.gov/books/NBK562184/' },
  { id: 'S107', title: 'StatPearls — Neuroanatomy, Cerebral Hemisphere', url: 'https://www.ncbi.nlm.nih.gov/books/NBK549789/' },
  { id: 'S108', title: 'Knecht et al. — Handedness and hemispheric language dominance in healthy humans (Brain, 2000)', url: 'https://academic.oup.com/brain/article/123/12/2512/325690' },
  { id: 'S109', title: 'StatPearls — Ataxia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK562284/' },
  { id: 'S110', title: 'StatPearls — Neuroanatomy, Cerebellum', url: 'https://www.ncbi.nlm.nih.gov/books/NBK538167/' },
  { id: 'S111', title: 'StatPearls — Cerebellar Dysfunction', url: 'https://www.ncbi.nlm.nih.gov/books/NBK562317/' },
  { id: 'S112', title: 'StatPearls — Neuroanatomy, Cerebellar Dysfunction', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545251/' },
  { id: 'S113', title: 'StatPearls — Cerebellar Infarction', url: 'https://www.ncbi.nlm.nih.gov/books/NBK470416/' },
  { id: 'S114', title: 'StatPearls — Vertebrobasilar Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556084/' },
  { id: 'S115', title: 'StatPearls — Pontine Infarction', url: 'https://www.ncbi.nlm.nih.gov/books/NBK554418/' },
  { id: 'S116', title: 'StatPearls — Parinaud Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK441892/' },
  { id: 'S117', title: 'StatPearls — Pupillary Light Reflex', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537180/' },
  { id: 'S118', title: 'StatPearls — Neuroanatomy, Pupillary Light Reflexes and Pathway', url: 'https://www.ncbi.nlm.nih.gov/books/NBK553169/' },
  { id: 'S119', title: 'StatPearls — Neuroanatomy, Mesencephalon Midbrain', url: 'https://www.ncbi.nlm.nih.gov/books/NBK551509/' },
  { id: 'S120', title: 'StatPearls — Neuroanatomy, Cranial Nerve 4 (Trochlear)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537244/' },
  { id: 'S121', title: 'StatPearls — Neuroanatomy, Trigeminal Reflexes', url: 'https://www.ncbi.nlm.nih.gov/books/NBK551641/' },
  { id: 'S122', title: 'StatPearls — Neuroanatomy, Cranial Nerve 5 (Trigeminal)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK482283/' },
  { id: 'S123', title: 'Walker — Cranial Nerve V: The Trigeminal Nerve, in Clinical Methods, 3rd edition (1990)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK384/' },
  { id: 'S124', title: 'StatPearls — Trochlear Nerve Palsy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK565850/' },
  { id: 'S125', title: 'StatPearls — Neuroanatomy, Subthalamic Nucleus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK559002/' },
  { id: 'S126', title: 'StatPearls — Neuroanatomy, Basal Ganglia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537141/' },
  { id: 'S127', title: 'StatPearls — Neuroanatomy, Substantia Nigra', url: 'https://www.ncbi.nlm.nih.gov/books/NBK536995/' },
  { id: 'S128', title: 'StatPearls — Gerstmann Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK519528/' },
  { id: 'S129', title: 'StatPearls — Neuroanatomy, Cerebral Cortex', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537247/' },
  { id: 'S130', title: 'Olaciregui Dague et al. — Gaze Palsy as a Manifestation of Todd’s Phenomenon (2020)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7287959/' },
  { id: 'S131', title: 'Steiner, Melamed — Conjugate eye deviation after acute hemispheric stroke (Annals of Neurology, 1984)', url: 'https://pubmed.ncbi.nlm.nih.gov/6497357/' },
  { id: 'S132', title: 'StatPearls — Locked-in Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK559026/' },
  { id: 'S133', title: 'Smith, Delargy — Locked-in syndrome (BMJ, 2005)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC549115/' },
  { id: 'S134', title: 'StatPearls — Anatomy, Head and Neck: Basilar Artery', url: 'https://www.ncbi.nlm.nih.gov/books/NBK459137/' },
  { id: 'S135', title: 'Caplan — "Top of the basilar" syndrome (Neurology, 1980)', url: 'https://pubmed.ncbi.nlm.nih.gov/7188637/' },
  { id: 'S136', title: 'Lieschke et al. — Symptoms, Imaging Features, Treatment Decisions, and Outcomes of Patients with Top of the Basilar Artery Syndrome (Neurocritical Care, 2025)', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12321678/' },
  { id: 'S137', title: 'StatPearls — Cortical Blindness', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560626/' },
  { id: 'S138', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Superficial Peroneal Nerve (Superficial Fibular Nerve)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK534793/' },
  { id: 'S139', title: 'StatPearls — Anatomy, Bony Pelvis and Lower Limb: Calf Deep Peroneal Nerve (Deep Fibular Nerve)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526033/' },
];
