// Registry of sources. Must match the table in docs/SOURCES.md exactly; a test compares
// ids, titles and links, so neither can drift from the other.
import type { SourceId } from './vocab.ts';

export const SOURCE_IDS: readonly SourceId[] = [
  'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'S12',
  'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19', 'S20', 'S21', 'S22', 'S23',
  'S24', 'S25', 'S26', 'S27', 'S28', 'S29', 'S30', 'S31', 'S32',
  'S33', 'S34', 'S35', 'S36', 'S37', 'S38', 'S39', 'S40', 'S41', 'S42', 'S43', 'S44', 'S45', 'S46',
  'S47', 'S48', 'S49', 'S50', 'S51', 'S52', 'S53', 'S54', 'S55', 'S56', 'S57', 'S58', 'S59', 'S60', 'S61', 'S62', 'S63', 'S64', 'S65', 'S66',
];

export type SourceRecord = { readonly id: SourceId; readonly title: string; readonly url: string };

export const SOURCES: readonly SourceRecord[] = [
  { id: 'S01', title: 'StatPearls — Brown-Séquard Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK538135/' },
  { id: 'S02', title: 'StatPearls — Spinal Shock', url: 'https://www.ncbi.nlm.nih.gov/books/NBK448163/' },
  { id: 'S03', title: 'StatPearls — Neurogenic Shock', url: 'https://www.ncbi.nlm.nih.gov/books/NBK459361/' },
  { id: 'S04', title: 'StatPearls — Autonomic Dysreflexia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK482434/' },
  { id: 'S05', title: 'MSD Manual Professional — Table: Spinal Cord Syndromes', url: 'https://www.msdmanuals.com/professional/multimedia/table/spinal-cord-syndromes' },
  { id: 'S06', title: 'StatPearls — Central Cord Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK441932/' },
  { id: 'S07', title: 'StatPearls — Anterior Spinal Artery Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560731/' },
  { id: 'S08', title: 'StatPearls — Syringomyelia', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537110/' },
  { id: 'S09', title: 'StatPearls — Cauda Equina and Conus Medullaris Syndromes', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537200/' },
  { id: 'S10', title: 'StatPearls — Spinal Cord Subacute Combined Degeneration', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560728/' },
  { id: 'S11', title: 'StatPearls — Neuroanatomy, Anterior White Commissure', url: 'https://www.ncbi.nlm.nih.gov/books/NBK546614/' },
  { id: 'S12', title: 'StatPearls — Deep Tendon Reflexes', url: 'https://www.ncbi.nlm.nih.gov/books/NBK531502/' },
  { id: 'S13', title: 'StatPearls — Tabes Dorsalis', url: 'https://www.ncbi.nlm.nih.gov/books/NBK557891/' },
  { id: 'S14', title: 'StatPearls — Neuroanatomy, Conus Medullaris', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545227/' },
  { id: 'S15', title: 'StatPearls — Spinal Cord Injuries', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560721/' },
  { id: 'S16', title: 'StatPearls — Horner Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK500000/' },
  { id: 'S17', title: 'StatPearls — Amyotrophic Lateral Sclerosis', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556151/' },
  { id: 'S18', title: 'StatPearls — Motor Neuron Disease', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560774/' },
  { id: 'S19', title: 'StatPearls — Cervical Radiculopathy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK441828/' },
  { id: 'S20', title: 'StatPearls — Neurogenic Bladder', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560617/' },
  { id: 'S21', title: 'StatPearls — Anatomy, Skin, Dermatomes', url: 'https://www.ncbi.nlm.nih.gov/books/NBK535401/' },
  { id: 'S22', title: 'StatPearls — Anatomy, Abdomen and Pelvis, Pudendal Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK554736/' },
  { id: 'S23', title: 'Brain Communications 2025 — The human spinothalamic tract: lessons from cordotomy', url: 'https://academic.oup.com/braincomms/article/7/3/fcaf237/8165923' },
  { id: 'S24', title: 'StatPearls — Neuroanatomy, Spinal Cord Morphology', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545206/' },
  { id: 'S25', title: 'StatPearls — Neuroanatomy, Touch Receptor', url: 'https://www.ncbi.nlm.nih.gov/books/NBK547731/' },
  { id: 'S26', title: 'Neuroscience Online (UTHealth) — Anatomy of the Spinal Cord, ch. 3', url: 'https://nba.uth.tmc.edu/neuroscience/m/s2/chapter03.html' },
  { id: 'S27', title: 'StatPearls — Neuroanatomy, Posterior Column', url: 'https://www.ncbi.nlm.nih.gov/books/NBK507888/' },
  { id: 'S28', title: 'StatPearls — Neuroanatomy, Unmyelinated Nerve Fibers', url: 'https://www.ncbi.nlm.nih.gov/books/NBK554461/' },
  { id: 'S29', title: 'Snooks & Swash, JNNP 1985 — Motor conduction velocity in the human spinal cord', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1028573/' },
  { id: 'S30', title: 'Radiopaedia — Spinal cord', url: 'https://radiopaedia.org/articles/spinal-cord' },
  { id: 'S31', title: 'StatPearls — Physiology, Spinal Cord', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544267/' },
  { id: 'S32', title: 'StatPearls — Cervical Injury', url: 'https://www.ncbi.nlm.nih.gov/books/NBK448146/' },
  { id: 'S33', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Brachial Plexus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK500016/' },
  { id: 'S34', title: 'StatPearls — Anatomy, Head and Neck: Brachial Plexus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK531473/' },
  { id: 'S35', title: 'StatPearls — Erb Palsy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK513260/' },
  { id: 'S36', title: 'StatPearls — Klumpke Palsy', url: 'https://www.ncbi.nlm.nih.gov/books/NBK531500/' },
  { id: 'S37', title: 'StatPearls — Electrodiagnostic Evaluation of Brachial Plexopathies', url: 'https://www.ncbi.nlm.nih.gov/books/NBK562197/' },
  { id: 'S38', title: 'StatPearls — Ulnar Nerve Entrapment', url: 'https://www.ncbi.nlm.nih.gov/books/NBK555929/' },
  { id: 'S39', title: 'StatPearls — Wrist Drop', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532993/' },
  { id: 'S40', title: 'StatPearls — Radial Nerve Injury', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537304/' },
  { id: 'S41', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Median Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK448084/' },
  { id: 'S42', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Axillary Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK493212/' },
  { id: 'S43', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Musculocutaneous Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK534199/' },
  { id: 'S44', title: 'StatPearls — Anatomy, Thorax, Long Thoracic Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK535396/' },
  { id: 'S45', title: 'StatPearls — Anatomy, Medial Antebrachial Cutaneous Nerve', url: 'https://www.ncbi.nlm.nih.gov/books/NBK551638/' },
  { id: 'S46', title: 'StatPearls — Anatomy, Shoulder and Upper Limb, Cutaneous Innervation', url: 'https://www.ncbi.nlm.nih.gov/books/NBK545249/' },
  { id: 'S47', title: 'StatPearls — Lateral Medullary Syndrome (Wallenberg Syndrome)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK551670/' },
  { id: 'S48', title: 'StatPearls — Medial Medullary Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560590/' },
  { id: 'S49', title: 'StatPearls — Millard-Gubler Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532907/' },
  { id: 'S50', title: 'StatPearls — Weber Syndrome', url: 'https://www.ncbi.nlm.nih.gov/books/NBK559158/' },
  { id: 'S51', title: 'StatPearls — Neuroanatomy, Cranial Nerve 7 (Facial)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526119/' },
  { id: 'S52', title: 'StatPearls — Middle Cerebral Artery Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK556132/' },
  { id: 'S53', title: 'StatPearls — Anterior Cerebral Artery Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK537333/' },
  { id: 'S54', title: 'StatPearls — Neuroanatomy, Precentral Gyrus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544218/' },
  { id: 'S55', title: 'StatPearls — Lacunar Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK563216/' },
  { id: 'S56', title: 'StatPearls — Neuroanatomy, Internal Capsule', url: 'https://www.ncbi.nlm.nih.gov/books/NBK542181/' },
  { id: 'S57', title: 'StatPearls — Neuroanatomy, Medial Lemniscus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526040/' },
  { id: 'S58', title: 'StatPearls — Neuroanatomy, Spinothalamic Tract', url: 'https://www.ncbi.nlm.nih.gov/books/NBK507824/' },
  { id: 'S59', title: 'StatPearls — Neuroanatomy, Brainstem', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544297/' },
  { id: 'S60', title: 'StatPearls — Neuroanatomy, Spinal Trigeminal Nucleus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK539729/' },
  { id: 'S61', title: 'StatPearls — Neuroanatomy, Abducens Nucleus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK544265/' },
  { id: 'S62', title: 'StatPearls — Cranial Nerve III Palsy (Oculomotor Palsy)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526112/' },
  { id: 'S63', title: 'StatPearls — Neuroanatomy, Cranial Nerve 12 (Hypoglossal)', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532869/' },
  { id: 'S64', title: 'StatPearls — Neuroanatomy, Nucleus Ambiguus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK547744/' },
  { id: 'S65', title: 'StatPearls — Brainstem Stroke', url: 'https://www.ncbi.nlm.nih.gov/books/NBK560896/' },
  { id: 'S66', title: 'StatPearls — Neurosurgery, Sensory Homunculus', url: 'https://www.ncbi.nlm.nih.gov/books/NBK549841/' },
];
