// Amendment A10. Reverse inference at the lower limb, written before any lower-limb code.
// Each case is an examination as the sources describe the lesion (docs/P7-analysis.md); each
// expectation is a property of the ranking. Where a source says two lesions cannot be told
// apart at the bedside, the expectation says so rather than demanding a single winner.
import type { Muscle, Reflex, ReflexObservation, SensoryObservation, Side, SkinArea, StrengthObservation } from '../../src/kb/vocab.ts';
import type { LimbObservation, LimbReverseCase } from './reverse-plexus.ts';

const m = (muscle: Muscle, value: StrengthObservation, side: Side = 'L'): LimbObservation => ({ kind: 'muscle', side, muscle, value });
const s = (area: SkinArea, value: SensoryObservation, side: Side = 'L'): LimbObservation => ({ kind: 'skin', side, area, value });
const r = (reflex: Reflex, value: ReflexObservation, side: Side = 'L'): LimbObservation => ({ kind: 'reflex', side, reflex, value });
const quietRight: LimbObservation[] = [
  m('tibialis_anterior', 'normal', 'R'),
  m('quadriceps', 'normal', 'R'),
  { kind: 'babinski', side: 'L', value: 'absent' },
  { kind: 'babinski', side: 'R', value: 'absent' },
];

export const LEG_REVERSE_CASES: readonly LimbReverseCase[] = [
  {
    id: 'reverse-common-fibular',
    title: 'Foot drop and weak eversion, with inversion and hip abduction strong',
    observations: [
      m('tibialis_anterior', 'weak'),
      m('toe_extensor', 'weak'),
      m('fibularis', 'weak'),
      m('tibialis_posterior', 'normal'),
      m('gluteus_medius', 'normal'),
      m('gastrocnemius', 'normal'),
      m('hamstrings', 'normal'),
      s('dorsum_foot', 'abnormal'),
      s('first_web', 'abnormal'),
      s('sole', 'normal'),
      s('medial_leg', 'normal'),
      r('achilles', 'normal'),
      r('patellar', 'normal'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', topFamily: 'nerve_left', topSites: ['common_fibular'] }],
    cite: ['S83', 'S77', 'S78'],
    basis: 'stated',
    note: 'Strong inversion and hip abduction rule out L5 (S83); strong plantar flexion and hamstrings rule out the sciatic nerve (S78).',
  },
  {
    id: 'reverse-root-L5',
    title: 'Foot drop with weak inversion and hip abduction, plantar flexion and knee extension strong',
    observations: [
      m('tibialis_anterior', 'weak'),
      m('toe_extensor', 'weak'),
      m('tibialis_posterior', 'weak'),
      m('gluteus_medius', 'weak'),
      m('gastrocnemius', 'normal'),
      m('quadriceps', 'normal'),
      s('dorsum_foot', 'abnormal'),
      s('medial_leg', 'normal'),
      s('lateral_foot', 'normal'),
      r('achilles', 'normal'),
      r('patellar', 'normal'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', topFamily: 'root_left', rostralEndWithin: ['L5', 'L5'], topFamilyNot: ['nerve_left', 'plexus_left'] }],
    cite: ['S83', 'S82', 'S78'],
    basis: 'stated',
    note: 'Weak inversion and hip abduction rule out the fibular nerve (S83); strong plantar flexion rules out the sciatic nerve and S1 (S78, S82).',
  },
  {
    id: 'reverse-sciatic',
    title: 'Flail foot, weak hamstrings, numb sole and dorsum, gluteal muscles strong',
    observations: [
      m('tibialis_anterior', 'weak'),
      m('gastrocnemius', 'weak'),
      m('tibialis_posterior', 'weak'),
      m('hamstrings', 'weak'),
      m('gluteus_medius', 'normal'),
      m('gluteus_maximus', 'normal'),
      m('quadriceps', 'normal'),
      s('sole', 'abnormal'),
      s('dorsum_foot', 'abnormal'),
      s('medial_leg', 'normal'),
      r('achilles', 'reduced'),
      r('patellar', 'normal'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', topFamily: 'nerve_left', topSites: ['sciatic'] }],
    cite: ['S78', 'S75'],
    basis: 'stated',
    note: 'S78: the whole foot and the hamstrings with the gluteal muscles spared; strong gluteus medius also rules out L5.',
  },
  {
    id: 'reverse-sacral-plexus',
    title: 'Flail foot and weak hamstrings with the gluteal muscles weak too',
    observations: [
      m('tibialis_anterior', 'weak'),
      m('gastrocnemius', 'weak'),
      m('hamstrings', 'weak'),
      m('gluteus_medius', 'weak'),
      m('gluteus_maximus', 'weak'),
      m('quadriceps', 'normal'),
      m('hip_adductors', 'normal'),
      s('sole', 'abnormal'),
      s('dorsum_foot', 'abnormal'),
      s('medial_leg', 'normal'),
      r('achilles', 'reduced'),
      r('patellar', 'normal'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', amongTop: { k: 2, families: [['plexus_left']] }, topFamilyNot: ['nerve_left'] }],
    cite: ['S78', 'S72'],
    basis: 'stated',
    note: 'Gluteal weakness moves the lesion above the sciatic nerve (S78). S72 separates plexus from roots by paraspinal denervation, which a bedside examination cannot see, so the roots L5–S2 may rank alongside.',
  },
  {
    id: 'reverse-femoral',
    title: 'Weak knee extension, reduced knee jerk, numb anterior thigh and medial leg, adduction strong',
    observations: [
      m('quadriceps', 'weak'),
      m('hip_adductors', 'normal'),
      m('tibialis_anterior', 'normal'),
      m('gastrocnemius', 'normal'),
      s('anterior_thigh', 'abnormal'),
      s('medial_leg', 'abnormal'),
      s('lateral_thigh', 'normal'),
      r('patellar', 'reduced'),
      r('achilles', 'normal'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', amongTop: { k: 2, families: [['nerve_left']] }, topFamilyNot: ['plexus_left'] }],
    cite: ['S89', 'S73', 'S88'],
    basis: 'stated',
    note: 'Strong adduction and a spared lateral thigh rule out the lumbar plexus (S73, S72); strong dorsiflexion argues against L4. S88: the broad L2–L4 overlap can leave an upper lumbar root beside the femoral nerve.',
  },
  {
    id: 'reverse-meralgia',
    title: 'Numb lateral thigh, nothing weak, knee jerk normal',
    observations: [
      s('lateral_thigh', 'abnormal'),
      s('anterior_thigh', 'normal'),
      s('medial_thigh', 'normal'),
      s('medial_leg', 'normal'),
      m('iliopsoas', 'normal'),
      m('quadriceps', 'normal'),
      m('hip_adductors', 'normal'),
      r('patellar', 'normal'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', amongTop: { k: 2, families: [['nerve_left']] }, topFamilyNot: ['plexus_left'] }],
    cite: ['S74'],
    basis: 'stated',
    note: 'A purely sensory nerve with no motor or reflex function (S74). A dorsal root at L2 or L3 could also numb the lateral thigh, which no source read separates at the bedside.',
  },
  {
    id: 'reverse-medial-malleolus',
    title: 'Numb medial malleolus with weak knee extension and a reduced knee jerk',
    observations: [
      { kind: 'sensory', side: 'L', modality: 'pain_temperature', span: ['L4', 'L4'], value: 'abnormal' },
      { kind: 'sensory', side: 'L', modality: 'pain_temperature', span: ['L5', 'L5'], value: 'normal' },
      { kind: 'sensory', side: 'L', modality: 'pain_temperature', span: ['S1', 'S1'], value: 'normal' },
      m('quadriceps', 'weak'),
      m('tibialis_anterior', 'weak'),
      m('gastrocnemius', 'normal'),
      r('patellar', 'reduced'),
      r('achilles', 'normal'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', topFamily: 'root_left', rostralEndWithin: ['L4', 'L4'] }],
    cite: ['S82', 'S88', 'S86'],
    basis: 'stated',
    note: 'S82 gives the medial malleolus, the quadriceps and the knee jerk to L4; the landmark is tested through the saphenous territory (S86).',
  },
  {
    id: 'reverse-lateral-foot',
    title: 'Numb lateral foot with weak plantar flexion and a lost ankle jerk',
    observations: [
      { kind: 'sensory', side: 'L', modality: 'pain_temperature', span: ['S1', 'S1'], value: 'abnormal' },
      { kind: 'sensory', side: 'L', modality: 'pain_temperature', span: ['L5', 'L5'], value: 'normal' },
      { kind: 'sensory', side: 'L', modality: 'pain_temperature', span: ['L4', 'L4'], value: 'normal' },
      m('gastrocnemius', 'weak'),
      m('tibialis_anterior', 'normal'),
      m('tibialis_posterior', 'normal'),
      // A31: "sole normal" was removed. It was composed in P7, when no source gave the sole roots;
      // S151 and S155 now put the sole in S1, so an S1 root does not leave it normal (D142).
      m('quadriceps', 'normal'),
      r('achilles', 'reduced'),
      r('patellar', 'normal'),
      // The other leg is examined too, which is what separates one root from both.
      m('gastrocnemius', 'normal', 'R'),
      r('achilles', 'normal', 'R'),
      ...quietRight,
    ],
    expectations: [{ timepoint: 'chronic', topFamily: 'root_left', rostralEndWithin: ['S1', 'S1'] }],
    cite: ['S82', 'S87', 'S83', 'S79'],
    basis: 'stated',
    note: 'S82 gives the lateral malleolus and lateral foot, plantar flexion and the Achilles reflex to S1; the landmark is tested through the sural territory (S87). Strong inversion separates the root from the tibial nerve, which supplies tibialis posterior (S83, S79); A31 removed the normal sole, which S151 and S155 put in S1.',
  },
  {
    id: 'reverse-foot-drop-open',
    title: 'Foot drop, nothing else examined at the leg',
    observations: [m('tibialis_anterior', 'weak'), ...quietRight],
    expectations: [{ timepoint: 'chronic', amongTop: { k: 4, families: [['nerve_left'], ['root_left']] }, nextTestSeparatesTopTwo: true }],
    cite: ['S78', 'S83'],
    basis: 'stated',
    note: 'Foot drop alone is fibular, L5, sciatic or plexus (S78); the tool must name a test that separates the leaders.',
  },
];
