// Writes the clinical review in two forms from one source (scripts/review-data.ts):
// review/worksheet.md to read or print, and review/review.html to fill in and save.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildWorksheet } from './review-data.ts';
import type { ReviewItem, Source } from './review-lib.ts';

const ROOT = resolve(import.meta.dirname, '..');
const ws = buildWorksheet();
const of = (s: ReviewItem['section']): ReviewItem[] => ws.items.filter((i) => i.section === s);
const cite = (xs: readonly Source[]): string => (xs.length === 0 ? '_none_' : xs.map((s) => `[${s.id}](${s.url})`).join(', '));
const box = '☐ right ☐ wrong ☐ unsure';
const claims = of('claim');
const facts = of('fact');
const questions = of('question');
const cases = of('case');
const composed = cases.reduce((n, c) => n + (c.findings?.length ?? 0), 0);

const out: string[] = [
  '# Clinical review worksheet',
  '',
  '_Generated by `npm run worksheet`. Do not edit by hand — regenerate it._',
  '',
  'Thank you for checking this. It is a teaching tool, not clinical software, and these',
  'claims are what it teaches. Mark each one; where a claim is wrong, a one-line correction',
  'with a source is the most useful thing you can give.',
  '',
  'The same review can be filled in on screen and saved to a file: `review/review.html`.',
  `Worksheet version \`${ws.version}\`.`,
  '',
  `${claims.length} knowledge-base claims, ${facts.length} displayed facts, ${questions.length} open questions, ${composed} composed findings in ${cases.length} cases. ${ws.score}`,
  'Claims are ordered by load-bearing weight: how many expected findings fail when the claim',
  'is corrupted. The first ten carry most of the engine.',
  '',
  '## 1. Knowledge-base claims',
  '',
];
const row = (m: ReviewItem): void => {
  out.push(`**${m.n}. ${m.title}**`);
  out.push([`\`${m.id}\``, ...m.tags, `sources ${m.definitional ? '_definitional_' : cite(m.sources)}`].join(' · '));
  if (m.warning) out.push(`> ⚠ No source read supports all of this. ${m.warning}`);
  out.push('', box, 'Correction and source (a book and page is ideal): ____', '');
};
claims.forEach(row);
out.push(
  '## 1b. Facts the tool displays',
  '',
  'These do not change any computed finding, but they are drawn or printed: segment and',
  'vertebra positions, myotomes, dermatome landmarks, fibre speeds and tract arrangement.',
  '',
);
facts.forEach(row);

out.push('## 2. Open questions', '', ...questions.map((q) => `- **${q.id}** — ${q.title}`), '');

out.push('## 3. Disputed mechanisms', '', 'For context. The engine never uses these; they drive only the teaching layer.', '');
for (const m of ws.mechanisms) {
  out.push(`**${m.claim}** (${m.tier})`);
  for (const p of m.positions) out.push(`- ${p.account} — ${cite(p.sources)}`);
  out.push('');
}

out.push(
  '## 4. Composed expectations',
  '',
  `${composed} expected findings are not stated by any single source; they follow from`,
  'several stated facts. They are the most likely place for a reasoning error. Each line is',
  'what the tool will teach for that lesion.',
  '',
);
for (const c of cases) {
  out.push(`### ${c.title} — _${c.subtitle ?? ''}_`, '');
  for (const f of c.findings ?? []) out.push(`- ☐ ${f.text} — ${cite(f.sources)}${f.note ? ` — _${f.note}_` : ''}`);
  out.push('');
}

mkdirSync(resolve(ROOT, 'review'), { recursive: true });
writeFileSync(resolve(ROOT, 'review', 'worksheet.md'), `${out.join('\n')}\n`);

// The page carries its data inline; `</` is escaped so no string can close the script.
const template = readFileSync(resolve(ROOT, 'review', 'page.template.html'), 'utf8');
const data = JSON.stringify(ws).replace(/</g, '\\u003c');
if (!template.includes('"__WORKSHEET__"')) throw new Error('review/page.template.html has no "__WORKSHEET__" slot');
writeFileSync(resolve(ROOT, 'review', 'review.html'), template.replace('"__WORKSHEET__"', () => data));

console.log(
  `review/worksheet.md and review/review.html (version ${ws.version}): ${claims.length} engine claims, ${facts.length} displayed facts, ${questions.length} questions, ${composed} composed findings in ${cases.length} cases`,
);
